// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDphZgUG62Y2RAjN1INODA-Sw1Jko6n4Ec',
    appId: '1:322501073712:web:21da36f62de1644d8bc6f5',
    messagingSenderId: '322501073712',
    projectId: 'fluttergram-a5de2',
    authDomain: 'fluttergram-a5de2.firebaseapp.com',
    storageBucket: 'fluttergram-a5de2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA521uyL_Mq880oIZHgCgY_DZSXWMrVL4g',
    appId: '1:322501073712:android:f2c39cc2e7dabd558bc6f5',
    messagingSenderId: '322501073712',
    projectId: 'fluttergram-a5de2',
    storageBucket: 'fluttergram-a5de2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCA_OmWQ1PTrRnsOG_wcUHLjVQaejbdTaE',
    appId: '1:322501073712:ios:a11b30c4b6c549e18bc6f5',
    messagingSenderId: '322501073712',
    projectId: 'fluttergram-a5de2',
    storageBucket: 'fluttergram-a5de2.appspot.com',
    iosClientId: '322501073712-hpenk2l2qqjijvpk81r3toi2btrlflb4.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebasePractice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCA_OmWQ1PTrRnsOG_wcUHLjVQaejbdTaE',
    appId: '1:322501073712:ios:a5bd029ea0a78dfd8bc6f5',
    messagingSenderId: '322501073712',
    projectId: 'fluttergram-a5de2',
    storageBucket: 'fluttergram-a5de2.appspot.com',
    iosClientId: '322501073712-s3b5b5f7cjadas6audstapl3cfpi1fve.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebasePractice.RunnerTests',
  );
}
