// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnG2CCs7bF0-y151UlQZSnX3H6-ziySoo',
    appId: '1:578525692226:web:d3e845528d315c4b4608db',
    messagingSenderId: '578525692226',
    projectId: 'chatappflutter-9edbf',
    authDomain: 'chatappflutter-9edbf.firebaseapp.com',
    storageBucket: 'chatappflutter-9edbf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnnZYYx-hnr3eTY3NmaQKtxh2J7-95J7c',
    appId: '1:578525692226:android:64f4fce0554990524608db',
    messagingSenderId: '578525692226',
    projectId: 'chatappflutter-9edbf',
    storageBucket: 'chatappflutter-9edbf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXQjFEcXV-Q3vMAXOx-dvs1suaR9WxqNk',
    appId: '1:578525692226:ios:6b7a63d7d2d9e0a54608db',
    messagingSenderId: '578525692226',
    projectId: 'chatappflutter-9edbf',
    storageBucket: 'chatappflutter-9edbf.appspot.com',
    androidClientId: '578525692226-19oad2lr3h8cb7rgmf0pv71hn9o7jumr.apps.googleusercontent.com',
    iosClientId: '578525692226-6pd2gb8ip4thcf2obm27sf6ptvdotp63.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebasePractice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXQjFEcXV-Q3vMAXOx-dvs1suaR9WxqNk',
    appId: '1:578525692226:ios:2bb712c3f1cea2cc4608db',
    messagingSenderId: '578525692226',
    projectId: 'chatappflutter-9edbf',
    storageBucket: 'chatappflutter-9edbf.appspot.com',
    androidClientId: '578525692226-19oad2lr3h8cb7rgmf0pv71hn9o7jumr.apps.googleusercontent.com',
    iosClientId: '578525692226-89ngkoc53utm1q53m1c5b4ivb1ep7qfk.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebasePractice.RunnerTests',
  );
}
